import type { Vehicle, Adapter, ChargingStation } from './types';

export const vehicles: Vehicle[] = [
  {
    id: 1,
    year: 2023,
    make: 'Tesla',
    model: 'Model Y',
    trim: 'Long Range',
    connectorType: ['NACS'],
    maxAcChargeRate: 11.5,
    maxDcChargeRate: 250,
    batteryCapacity: 81,
    range: 330,
    imageUrl: 'vehicle-1',
  },
  {
    id: 2,
    year: 2024,
    make: 'Ford',
    model: 'Mustang Mach-E',
    trim: 'GT',
    connectorType: ['CCS'],
    maxAcChargeRate: 10.5,
    maxDcChargeRate: 150,
    batteryCapacity: 91,
    range: 270,
    imageUrl: 'vehicle-2',
  },
  {
    id: 3,
    year: 2023,
    make: 'Hyundai',
    model: 'IONIQ 5',
    trim: 'Limited',
    connectorType: ['CCS'],
    maxAcChargeRate: 10.9,
    maxDcChargeRate: 233,
    batteryCapacity: 77.4,
    range: 266,
    imageUrl: 'vehicle-3',
  },
  {
    id: 4,
    year: 2022,
    make: 'Nissan',
    model: 'Leaf',
    trim: 'SV PLUS',
    connectorType: ['CHAdeMO', 'J1772'],
    maxAcChargeRate: 6.6,
    maxDcChargeRate: 100,
    batteryCapacity: 62,
    range: 212,
    imageUrl: 'vehicle-4',
  },
];

export const adapters: Adapter[] = [
  {
    id: 1,
    name: 'Tesla to J1772 Adapter',
    from: 'NACS',
    to: 'J1772',
    certification: 'OEM',
    price: 50,
    purchaseUrl: '#',
    imageUrl: '1',
    imageHint: 'adapter cable',
  },
  {
    id: 2,
    name: 'Lectron CCS to Tesla Adapter',
    from: 'CCS',
    to: 'NACS',
    certification: 'UL 2252',
    price: 199,
    purchaseUrl: '#',
    imageUrl: '2',
    imageHint: 'adapter cable',
  },
  {
    id: 3,
    name: 'CHAdeMO to Tesla Adapter',
    from: 'CHAdeMO',
    to: 'NACS',
    certification: 'OEM',
    price: 450,
    purchaseUrl: '#',
    imageUrl: '3',
    imageHint: 'adapter cable',
  },
];

export const stations: ChargingStation[] = [
  {
    id: 1,
    name: 'Electrify America Supercenter',
    address: '123 Main St, San Francisco, CA',
    position: { lat: 37.7749, lng: -122.4194 },
    connectors: [
      { type: 'CCS', power: 350, status: 'Available' },
      { type: 'CCS', power: 150, status: 'InUse' },
      { type: 'CHAdeMO', power: 50, status: 'OutOfOrder' },
    ],
    chargeSuccessScore: 92,
    pricing: '$0.48/kWh',
    streetViewImageUrl: '4',
    streetViewImageHint: 'parking lot',
  },
  {
    id: 2,
    name: 'EVgo Fast Charging',
    address: '456 Market St, San Francisco, CA',
    position: { lat: 37.7936, lng: -122.3989 },
    connectors: [
      { type: 'CCS', power: 150, status: 'Available' },
      { type: 'CHAdeMO', power: 50, status: 'Available' },
    ],
    chargeSuccessScore: 78,
    pricing: '$0.35/kWh + session fee',
    streetViewImageUrl: '5',
    streetViewImageHint: 'street side parking',
  },
  {
    id: 3,
    name: 'Tesla Supercharger',
    address: '789 Mission St, San Francisco, CA',
    position: { lat: 37.782, lng: -122.406 },
    connectors: [
      { type: 'NACS', power: 250, status: 'Available' },
      { type: 'NACS', power: 250, status: 'Available' },
      { type: 'NACS', power: 250, status: 'InUse' },
    ],
    chargeSuccessScore: 98,
    pricing: 'Varies, ~$0.40/kWh',
    streetViewImageUrl: '6',
    streetViewImageHint: 'garage interior',
  },
  {
    id: 4,
    name: 'Public Library L2 Charger',
    address: '100 Larkin St, San Francisco, CA',
    position: { lat: 37.779, lng: -122.416 },
    connectors: [{ type: 'J1772', power: 7, status: 'Available' }],
    chargeSuccessScore: 65,
    pricing: 'Free for 2 hours',
    streetViewImageUrl: '7',
    streetViewImageHint: 'parking garage',
  },
];
